#! /bin/bash

#
# Installs and builds the various dependencies.
# Should probably migrate to package.el at some point.
#

#
# package versions
#
CEDET_VER=1.0.1
ORG_VER=7.8.08


#
# .emacs symlink
#
if [ -e ~/.emacs ]; then
    rm -f ~/.emacs
fi
ln -s ~/.emacs.d/.emacs ~/.emacs

pushd .
cd vendor

#
# CEDET package
#
rm -rf cedet-$CEDET_VET
tar xzf cedet-$CEDET_VER.tar.gz
pushd .
cd cedet-$CEDET_VER
make -j2 EMACS=emacs # MAKEINFO=echo # in case makeinfo isn't available.
popd
ln -s cedet-$CEDET_VER cedet

#
# org-mode package
#
rm -rf org-$ORG_VER
tar xzf org-$ORG_VER.tar.gz
pushd .
cd org-$ORG_VER
make -j2
popd
ln -s org-$ORG_VER org


popd